# - name: set user.name
#   command: "git config --global user.name 'kanais7'"
#   changed_when: false

# - name: set user.email
#   command: "git config --global user.email 'kanais0620@gmail.com'"
#   changed_when: false

# - name: enable autosquash
#   command: "git config --global rebase.autosquash true"
#   changed_when: false

- name: copy global ignore
  copy:
    src: .gitignore_global
    dest: ~/.gitignore_global

# - name: apply global ignore
#   command: "git config --global core.excludesfile ~/.gitignore_global"
#   changed_when: false

- name: copy git config
  copy:
    src: .gitconfig
    dest: ~/.gitconfig
